require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConfigurationsController do

  # This should return the minimal set of attributes required to create a valid
  # Configuration. As you add validations to Configuration, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET show" do
    it "assigns the requested configuration as @configuration" do
      configuration = Configuration.create! valid_attributes
      get :show, :id => configuration.id
      assigns(:configuration).should eq(configuration)
    end
  end

  describe "GET new" do
    it "assigns a new configuration as @configuration" do
      get :new
      assigns(:configuration).should be_a_new(Configuration)
    end
  end

  describe "GET edit" do
    it "assigns the requested configuration as @configuration" do
      configuration = Configuration.create! valid_attributes
      get :edit, :id => configuration.id
      assigns(:configuration).should eq(configuration)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Configuration" do
        expect {
          post :create, :configuration => valid_attributes
        }.to change(Configuration, :count).by(1)
      end

      it "assigns a newly created configuration as @configuration" do
        post :create, :configuration => valid_attributes
        assigns(:configuration).should be_a(Configuration)
        assigns(:configuration).should be_persisted
      end

      it "redirects to the created configuration" do
        post :create, :configuration => valid_attributes
        response.should redirect_to(Configuration.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved configuration as @configuration" do
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration.any_instance.stub(:save).and_return(false)
        post :create, :configuration => {}
        assigns(:configuration).should be_a_new(Configuration)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration.any_instance.stub(:save).and_return(false)
        post :create, :configuration => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested configuration" do
        configuration = Configuration.create! valid_attributes
        # Assuming there are no other configurations in the database, this
        # specifies that the Configuration created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Configuration.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => configuration.id, :configuration => {'these' => 'params'}
      end

      it "assigns the requested configuration as @configuration" do
        configuration = Configuration.create! valid_attributes
        put :update, :id => configuration.id, :configuration => valid_attributes
        assigns(:configuration).should eq(configuration)
      end

      it "redirects to the configuration" do
        configuration = Configuration.create! valid_attributes
        put :update, :id => configuration.id, :configuration => valid_attributes
        response.should redirect_to(configuration)
      end
    end

    describe "with invalid params" do
      it "assigns the configuration as @configuration" do
        configuration = Configuration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration.any_instance.stub(:save).and_return(false)
        put :update, :id => configuration.id, :configuration => {}
        assigns(:configuration).should eq(configuration)
      end

      it "re-renders the 'edit' template" do
        configuration = Configuration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration.any_instance.stub(:save).and_return(false)
        put :update, :id => configuration.id, :configuration => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested configuration" do
      configuration = Configuration.create! valid_attributes
      expect {
        delete :destroy, :id => configuration.id
      }.to change(Configuration, :count).by(-1)
    end

    it "redirects to the configurations list" do
      configuration = Configuration.create! valid_attributes
      delete :destroy, :id => configuration.id
      response.should redirect_to(configurations_url)
    end
  end

end
