require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RemotePermissionsController do

  # This should return the minimal set of attributes required to create a valid
  # RemotePermission. As you add validations to RemotePermission, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all remote_permissions as @remote_permissions" do
      remote_permission = RemotePermission.create! valid_attributes
      get :index
      assigns(:remote_permissions).should eq([remote_permission])
    end
  end

  describe "GET show" do
    it "assigns the requested remote_permission as @remote_permission" do
      remote_permission = RemotePermission.create! valid_attributes
      get :show, :id => remote_permission.id
      assigns(:remote_permission).should eq(remote_permission)
    end
  end

  describe "GET new" do
    it "assigns a new remote_permission as @remote_permission" do
      get :new
      assigns(:remote_permission).should be_a_new(RemotePermission)
    end
  end

  describe "GET edit" do
    it "assigns the requested remote_permission as @remote_permission" do
      remote_permission = RemotePermission.create! valid_attributes
      get :edit, :id => remote_permission.id
      assigns(:remote_permission).should eq(remote_permission)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RemotePermission" do
        expect {
          post :create, :remote_permission => valid_attributes
        }.to change(RemotePermission, :count).by(1)
      end

      it "assigns a newly created remote_permission as @remote_permission" do
        post :create, :remote_permission => valid_attributes
        assigns(:remote_permission).should be_a(RemotePermission)
        assigns(:remote_permission).should be_persisted
      end

      it "redirects to the created remote_permission" do
        post :create, :remote_permission => valid_attributes
        response.should redirect_to(RemotePermission.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved remote_permission as @remote_permission" do
        # Trigger the behavior that occurs when invalid params are submitted
        RemotePermission.any_instance.stub(:save).and_return(false)
        post :create, :remote_permission => {}
        assigns(:remote_permission).should be_a_new(RemotePermission)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RemotePermission.any_instance.stub(:save).and_return(false)
        post :create, :remote_permission => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested remote_permission" do
        remote_permission = RemotePermission.create! valid_attributes
        # Assuming there are no other remote_permissions in the database, this
        # specifies that the RemotePermission created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RemotePermission.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => remote_permission.id, :remote_permission => {'these' => 'params'}
      end

      it "assigns the requested remote_permission as @remote_permission" do
        remote_permission = RemotePermission.create! valid_attributes
        put :update, :id => remote_permission.id, :remote_permission => valid_attributes
        assigns(:remote_permission).should eq(remote_permission)
      end

      it "redirects to the remote_permission" do
        remote_permission = RemotePermission.create! valid_attributes
        put :update, :id => remote_permission.id, :remote_permission => valid_attributes
        response.should redirect_to(remote_permission)
      end
    end

    describe "with invalid params" do
      it "assigns the remote_permission as @remote_permission" do
        remote_permission = RemotePermission.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RemotePermission.any_instance.stub(:save).and_return(false)
        put :update, :id => remote_permission.id, :remote_permission => {}
        assigns(:remote_permission).should eq(remote_permission)
      end

      it "re-renders the 'edit' template" do
        remote_permission = RemotePermission.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RemotePermission.any_instance.stub(:save).and_return(false)
        put :update, :id => remote_permission.id, :remote_permission => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested remote_permission" do
      remote_permission = RemotePermission.create! valid_attributes
      expect {
        delete :destroy, :id => remote_permission.id
      }.to change(RemotePermission, :count).by(-1)
    end

    it "redirects to the remote_permissions list" do
      remote_permission = RemotePermission.create! valid_attributes
      delete :destroy, :id => remote_permission.id
      response.should redirect_to(remote_permissions_url)
    end
  end

end
